projects:
  dapdataset-dev:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: eu-central-1
        apiId: wecff4zw5jhcxdgreyir2nfgge
        maxDepth: 2
extensions:
  amplify:
    version: 3
