spring:

  datasource:
    url: jdbc:h2:file:/Users/marclecoultre/IdeaProjects/Annotation_backend/data/demo

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
    defer-datasource-initialization: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_1cFVgcU36
