spring:
  data:
    rest:
      base-path: /api

  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://fg-ai4h-db.cluster-cllejqtoj5fh.eu-central-1.rds.amazonaws.com:3306/fg_ai4h
    username: springuser
    password: password
    driver-class-name: com.mysql.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          cognito:
            clientId: 75n5jtgqafrue02lr8prk0kn3c
            clientSecret: 1sgfpgrg3cgkmhcq0inn6ga6sag5couic8h78f9gu1dod6m00o27
            scope: openid
            redirect-uri: https://annotation.ai4h.net/login/oauth2/code/cognito
            clientName: fg-ai4h-oc-prod
        provider:
          cognito:
            issuerUri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_1cFVgcU36
            user-name-attribute: cognito:username


