spring:
  data:
    rest:
      base-path: /api

  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    #url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/fg_ai4h
    url: jdbc:mysql://fg-ai4h-db.cluster-cllejqtoj5fh.eu-central-1.rds.amazonaws.com:3306/fg_ai4h
    username: springuser
    password: password
    driver-class-name: com.mysql.jdbc.Driver

#spring.jpa.show-sql: true

  security:
    oauth2:
      client:
        registration:
          cognito:
            clientId: 1moona5kt5r1brjqr3jgl5dkch
            clientSecret: tkkt3l2mo4aq7bfau3k4ster1k3gft1n8r9cc2sh19oihfnai6p
            scope: openid
            redirect-uri: http://localhost:8080/login/oauth2/code/cognito
            clientName: fg-ai4h-oc-dev
        provider:
          cognito:
            issuerUri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_1cFVgcU36
            user-name-attribute: cognito:username
